using ExpenseFlow.Domain.Entities;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace ExpenseFlow.Worker.Core.Handlers;

/// <summary>
/// Ledger item B4: PdfSharp 1.50 over GDI+ replaced with QuestPDF.
///
/// The original drew through XGraphics, which is GDI+ backed, and needed
/// manual cursor arithmetic plus hand-rolled pagination - the source of a
/// real bug where the graphics surface stayed bound to the first page.
///
/// QuestPDF is a layout engine, so pagination is automatic and the page-break
/// bug cannot recur by construction. Content and ordering are unchanged so
/// the output can be diffed against the pre-migration baseline.
/// </summary>
public static class ClaimPdfWriter
{
    static ClaimPdfWriter()
    {
        // QuestPDF is free under the Community licence below a revenue
        // threshold; larger commercial use requires a paid licence. Recorded
        // in the ledger, because System.Drawing had no such condition.
        QuestPDF.Settings.License = LicenseType.Community;
    }

    public static string Write(string pdfRoot, ExpenseClaim claim)
    {
        Directory.CreateDirectory(pdfRoot);

        var fullPath = Path.Combine(pdfRoot, claim.ClaimNumber + ".pdf");
        var lines = claim.Lines.OrderBy(l => l.ExpenseDate).ToList();

        Document.Create(document =>
        {
            document.Page(page =>
            {
                page.Size(PageSizes.A4);
                page.Margin(45);
                page.DefaultTextStyle(t => t.FontSize(9).FontFamily(Fonts.Verdana));

                page.Header().Column(header =>
                {
                    header.Item().Text("Expense claim " + claim.ClaimNumber)
                        .FontSize(16).Bold();
                    header.Item().PaddingTop(8).Text(claim.Title ?? string.Empty);
                    header.Item().Text("Claimant: " + (claim.Employee?.FullName ?? "(unknown)"));
                    header.Item().Text("Project: " + (claim.Project?.DisplayName ?? "(none)"));
                    header.Item().Text("Submitted: " + (claim.SubmittedUtc.HasValue
                        ? claim.SubmittedUtc.Value.ToString("yyyy-MM-dd HH:mm") + " UTC"
                        : "(not submitted)"));
                    header.Item().PaddingTop(14).LineHorizontal(0.5f).LineColor(Colors.Grey.Medium);
                });

                page.Content().PaddingVertical(10).Table(table =>
                {
                    table.ColumnsDefinition(columns =>
                    {
                        columns.ConstantColumn(70);   // date
                        columns.ConstantColumn(95);   // category
                        columns.RelativeColumn();     // description
                        columns.ConstantColumn(70);   // amount
                    });

                    table.Header(h =>
                    {
                        h.Cell().Text("Date").Bold();
                        h.Cell().Text("Category").Bold();
                        h.Cell().Text("Description").Bold();
                        h.Cell().AlignRight().Text("Amount").Bold();
                        h.Cell().ColumnSpan(4).PaddingTop(4)
                            .LineHorizontal(0.5f).LineColor(Colors.Grey.Medium);
                    });

                    foreach (var line in lines)
                    {
                        table.Cell().PaddingVertical(3).Text(line.ExpenseDate.ToString("yyyy-MM-dd"));
                        table.Cell().PaddingVertical(3).Text(line.Category?.Name ?? string.Empty);
                        table.Cell().PaddingVertical(3).Text(line.Description ?? string.Empty);
                        table.Cell().PaddingVertical(3).AlignRight().Text(line.Amount.ToString("N2"));
                    }

                    table.Cell().ColumnSpan(4).PaddingTop(4)
                        .LineHorizontal(0.5f).LineColor(Colors.Grey.Medium);

                    table.Cell().ColumnSpan(2);
                    table.Cell().PaddingTop(6).Text("Total").Bold();
                    table.Cell().PaddingTop(6).AlignRight()
                        .Text(claim.TotalAmount.ToString("N2") + " USD").Bold();
                });

                page.Footer().PaddingTop(10).Text(
                        "Generated by the ExpenseFlow worker on "
                        + DateTime.UtcNow.ToString("yyyy-MM-dd HH:mm") + " UTC")
                    .FontSize(7).Italic().FontColor(Colors.Grey.Darken1);
            });
        })
        .GeneratePdf(fullPath);

        return fullPath;
    }
}
